<script>
	import Col from 'sveltestrap/src/Col.svelte';
</script>

<Col>
  <h2 class="text-center">Contrats</h2>
  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Est reiciendis magni illo similique in nisi perspiciatis hic labore provident itaque! Minima asperiores repudiandae quia quis, nesciunt laborum expedita atque pariatur quam esse. Temporibus ipsum neque nesciunt in, corrupti modi expedita ea vel est hic iste debitis explicabo repellendus veritatis laboriosam praesentium, doloremque, exercitationem quasi reprehenderit? Aperiam error quae velit exercitationem molestias, sequi rerum totam omnis voluptate repellendus aut assumenda aliquid voluptatem amet. Libero perspiciatis voluptatibus sapiente architecto ad animi omnis quod pariatur, ipsum obcaecati accusamus nostrum magni ut quos beatae aliquid, laborum sequi cupiditate nam alias voluptas cum! Eveniet, facere.</p>
  <p>Voluptatem aspernatur dicta, quod, ducimus facilis cum suscipit nostrum at amet aperiam quaerat sint animi sunt soluta iste molestiae fugiat, nam itaque laudantium deserunt asperiores est eos. Ab quis repudiandae molestiae error doloribus necessitatibus nihil perspiciatis, ipsum esse est ipsam ducimus reprehenderit perferendis, delectus quod dolorum corporis explicabo quam, a excepturi totam fuga optio nobis dolorem. Ipsam voluptatum, fuga quas mollitia nisi, iusto atque temporibus aspernatur distinctio a sint assumenda corporis iste dolores fugiat! Fugiat, labore ad sunt eos voluptatibus architecto saepe hic similique facilis fugit numquam fuga odit optio expedita consectetur necessitatibus incidunt perspiciatis odio unde temporibus assumenda maxime.</p>
  <p>Suscipit modi odit, nostrum harum cupiditate expedita dignissimos obcaecati provident, vel adipisci saepe ipsam, pariatur dicta iure eius placeat aliquam atque ab porro cumque! Quos qui nesciunt, porro neque laborum delectus nihil dolor earum tenetur, error commodi mollitia optio ducimus ratione! Corrupti veniam, reiciendis, labore asperiores animi placeat dolores id omnis non sequi expedita ab quaerat illum. Rem repudiandae, sapiente iste error corrupti, repellat in hic suscipit veniam aliquid impedit vel corporis obcaecati? Cupiditate aspernatur rerum libero quidem quaerat minima fuga? Fugiat recusandae magnam ratione libero delectus quae soluta sapiente. Quasi soluta unde sint aut tempora veritatis harum eius deserunt.</p>
  <p>Veritatis reprehenderit placeat, rerum hic quisquam odit enim pariatur. Labore ab nemo at sint maiores sit sed dolor ducimus quidem cumque laborum accusamus pariatur excepturi, nesciunt eos ipsum earum cupiditate! Vitae nam et, delectus distinctio nemo odio reprehenderit ipsa cupiditate dolore quos nesciunt quaerat beatae doloribus explicabo sint culpa laudantium deserunt sapiente. Quis nulla adipisci officiis totam. Officia recusandae voluptatem id repudiandae molestiae consectetur, veritatis maiores laudantium cumque nemo praesentium unde rem minima quibusdam excepturi! Reiciendis quis maxime nisi fugit facilis accusantium, saepe eaque. Aliquam atque id, ab accusamus suscipit, sit quae tenetur porro dignissimos voluptates debitis eos numquam exercitationem?</p>
  <p>Illo quos quasi quisquam delectus, unde atque veritatis voluptates amet excepturi! Eum praesentium debitis qui rerum magni excepturi aperiam dolores exercitationem amet vitae porro nulla rem itaque provident deserunt quibusdam commodi, corrupti iusto facilis! Tempore dolorem minima itaque possimus ut nisi quia quod commodi. Dolorem aut fuga eum iusto odit rem veritatis natus officia, officiis minus amet ratione veniam, enim tenetur quasi culpa debitis. Temporibus vel fugiat recusandae ea, consectetur quaerat ipsum iusto officia nihil blanditiis voluptatem asperiores reprehenderit in labore, natus harum eligendi perferendis? Nesciunt, incidunt sit. Doloremque asperiores totam reiciendis natus ipsum non voluptates quam corporis consequatur nesciunt?</p>
</Col>